#!/usr/bin/env php
<?php

/**
 * if we're running from phar load the phar autoload,
 * else let the script 'robo' search for the autoloader
 */
if (strpos(basename(__FILE__), 'phar')) {
    require_once 'phar://robo.phar/vendor/autoload.php';
} else {
    if (file_exists(__DIR__.'/vendor/autoload.php')) {
        require_once __DIR__.'/vendor/autoload.php';
    } elseif (file_exists(__DIR__.'/../../autoload.php')) {
        require_once __DIR__ . '/../../autoload.php';
    } else {
        require_once 'phar://robo.phar/vendor/autoload.php';
    }
}
$_SERVER['CWD'] = getcwd();
if( file_exists( $_SERVER['HOME'].'/.mpm/RoboFile.php' ) ) 
{   
        $_SERVER['argv'][] = '--load-from';
        $_SERVER['argv'][] = $_SERVER['HOME'].'/.mpm/RoboFile.php';
}
$runner = new \Robo\Runner();
$statusCode = $runner->execute($_SERVER['argv']);
exit($statusCode);
